[package]
name = "issuecraft-common"
version.workspace = true
edition.workspace = true

[dependencies]
issuecraft-ql.workspace = true
thiserror.workspace = true
facet.workspace = true
facet-json.workspace = true
async-trait.workspace = true
time.workspace = true
