[package]
name = "issuecraft-common"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
facet.workspace = true
chrono.workspace = true
async-trait.workspace = true
serde.workspace = true
